#page title
page_title                                : EcoMonitor

# App Info
ios_app_id                                : 1234793120
ios_app_country                           : gb

appstore_link                             :
playstore_link                            : https://github.com/pi-drate/EcoMonitor/zipball/main
presskit_download_link                    : 


app_icon                                  : assets/logo_small.png
app_name                                  : EcoMonitor
app_price                                 : Free
app_description                           : Remotely monitor your irrigation system.

enable_smart_app_banner                   : true



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Instant data collection
    description                           : The short delay between collecting and displaying the data makes all farmers happy :)
    fontawesome_icon_name                 : magic
    
  - title                                 : App
    description                           : The app has an easy user-interface that should be accessible to everyone regardless of technological experience.
    fontawesome_icon_name                 : mobile

  - title                                 : Multitude of environmental assessments
    description                           : The app isn't only restricted to soil moisture, but also temperature, humidity and pressure.
    fontawesome_icon_name                 : play-circle

  - title                                 : Ability to treck on soil
    description                           : The wheels have ridges inside that grip well to soil, allowing the robot to better withstand farm conditions.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : 
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Information About Yourself
your_name                                 : Team Tera                                
your_link                                 :                      
your_city                                 :                             
email_address                             : sophieoztoprak@gmail.com
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : pi-drate
youtube_username                          : Sophie Oztoprak


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
